fagun-student:
 username: fagun.bhavsar@gmail.com
 password: Fagun@456
 description: a student user with no vocabulary assigned

fagun-site-admin:
  username: fagun@zinclearninglabs.com
  password: Fagun@456
  description: a site admin user

fagun-teacher:
  username: bfagun@yahoo.co.in
  password: Fagun@456
  description:  a teacher user

fagun-school-admin:
  username: fagun+admin@zinclearninglabs.com
  password: Fagun@456
  description:  a school admin user